"""esquema inicial

Revision ID: b4dfa1dfebf8
Revises: 
Create Date: 2026-09-13 15:31:29.960866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4dfa1dfebf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('actividad', sa.String(length=80), nullable=False),
    sa.Column('momento', sa.String(length=10), nullable=True),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("momento IN ('pre', 'post')", name='sesiones_momento_check'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sesiones_usuario', 'sesiones', ['usuario_id'], unique=False)
    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disponible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diagnosticos_sesion', 'diagnosticos', ['sesion_id'], unique=False)
    op.create_table('mediciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('actividad', sa.String(length=80), nullable=False),
    sa.Column('ear', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('perclos', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('parpadeos_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tiempo_cierre', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('velocidad_ocular', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('nivel_subjetivo', sa.SmallInteger(), nullable=True),
    sa.Column('nivel_fatiga', sa.String(length=20), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nivel_subjetivo BETWEEN 1 AND 5', name='mediciones_nivel_subjetivo_check'),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mediciones_sesion', 'mediciones', ['sesion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mediciones_sesion', table_name='mediciones')
    op.drop_table('mediciones')
    op.drop_index('idx_diagnosticos_sesion', table_name='diagnosticos')
    op.drop_table('diagnosticos')
    op.drop_index('idx_sesiones_usuario', table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
